# Generated by Django 3.2.7 on 2021-09-14 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('type', models.IntegerField(default=0, max_length=2)),
                ('code', models.CharField(max_length=21)),
                ('x', models.DateTimeField()),
                ('y', models.DateTimeField()),
            ],
            options={
                'proxy': False,
            },
        ),
        migrations.CreateModel(
            name='Depots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('type', models.IntegerField(default=0, max_length=2)),
                ('code', models.CharField(max_length=21)),
                ('x', models.DateTimeField()),
                ('y', models.DateTimeField()),
            ],
            options={
                'proxy': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('type', models.IntegerField(default=0, max_length=2)),
                ('code', models.CharField(max_length=21)),
                ('x', models.DateTimeField()),
                ('y', models.DateTimeField()),
            ],
            options={
                'proxy': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=21)),
                ('nombrecompat', models.IntegerField(max_length=3)),
                ('capacitecompat', models.IntegerField(max_length=3)),
                ('cout', models.PositiveIntegerField(max_length=10)),
            ],
            options={
                'proxy': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(max_length=2)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provider')),
            ],
        ),
    ]
